github.owner=CelinaBenedito
github.repo=ControleFinanceiro
# URL do arquivo de configuração do Update4j hospedado no GitHub (branch main ou gh-pages)
update4j.config.url=https://raw.githubusercontent.com/CelinaBenedito/ControleFinanceiro/main/update4j-config.xml
# Nome do asset JAR principal nos releases do GitHub
app.jar.name=back-end.jar
# Diretório local onde o JAR da aplicação é armazenado (relativo ao launcher)
app.dir=app

