spring.application.name=back-end

#Config para testes
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:teste;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
server.error.include-message=always
springdoc.swagger-ui.operationsSorter=method

#Config para deploy
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:mysql://localhost:3306/controle
#spring.datasource.username=aluno
#spring.datasource.password=sptech
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.defer-datasource-initialization=true
